name: CI - Run TestNG Suites with Maven

on:
  #  push:
  #    branches: ["main"]
  #  pull_request:
  #    branches: ["main"]
  workflow_dispatch:

jobs:
  run-tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          # - suite: testplan.xml
          #   logName: TestPlan_Log
          # - suite: requirement.xml
          #   logName: Requirement_Log
          # - suite: authortest.xml
          #   logName: Author_Log
          # - suite: executetest.xml
          #   logName: Execute_Log
          - suite: settings.xml
            logName: Setting_Log
          # - suite: defecttest.xml
          #   logName: Defect_Log

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "temurin"
          cache: maven

      - name: Build with Maven
        run: mvn -B clean install -DskipTests

      - name: Run TestNG Suite - ${{ matrix.suite }}
        continue-on-error: true
        run: |
          mvn test \
            -DsuiteXmlFile=TestRun_XML/${{ matrix.suite }} \
            -Dbrowser=chrome \
            -Dmode=headless \
            -DlogName=${{ matrix.logName }}

      - name: Prepare Surefire Report for Upload - ${{ matrix.suite }}
        if: always()
        run: |
          mkdir -p reports/${{ matrix.suite }}
          cp target/surefire-reports/emailable-report.html reports/${{ matrix.suite }}/ || echo "Surefire report not found."

      - name: Upload Surefire Report - ${{ matrix.suite }}
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: surefire-report-${{ matrix.suite }}
          path: reports/${{ matrix.suite }}/emailable-report.html

      - name: Prepare Extent Report for Upload - ${{ matrix.suite }}
        if: always()
        run: |
          mkdir -p reports/${{ matrix.suite }}
          cp target/extent-report.html reports/${{ matrix.suite }}/ || echo "Extent report not found."

      - name: Upload Extent Report - ${{ matrix.suite }}
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: extent-report-${{ matrix.suite }}
          path: reports/${{ matrix.suite }}/extent-report.html
